### PR TITLE
Made validator page only accessible when users are signed in. Used…

### LINKED ISSUE #10: Router Bug
If a user attempts to log in without proper credentials, they are sent to the /validator page. This page is blank because they don't have permission to access it. Ideally, the user would remain on the login page if they enter the incorrect credentials.

### PR DESCRIPTION
**Pull request by masonmcelvain**
… Redirect to change the lander page based on whether users are signed in or not. Passed setSignedIn to the SignOut and Login components so that they can update the state of App. Not sure if this is best practice, so would appreciate input on that.

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -9,18 +9,13 @@ import SignUp from "./pages/SignUp/SignUp";
...
     auth.onAuthStateChanged((user) => {
-      if (user) {
-        setSignedIn(true);
-        setUser(auth.currentUser);
-      } else {
-        setSignedIn(false);
-        setUser(""); 
-      }
+      setUser(auth.currentUser);
+      user ? setSignedIn(true) : setSignedIn(false);
```
Comment (Waidhoferj) [inline src/App.js:18]: Nice refinements!

File: src/App.js [hunk 2]
```diff
@@ -32,14 +27,21 @@ function App() {
         <Switch>
           <Route path="/signUp" exact component={SignUp} />
           <Route path="/forgotPassword" exact component={ForgotPassword} />
-          <Route path="/login" exact component={Login} />
+          <Route path="/login" exact render={() =>
+            <Login
+              setSignedIn={setSignedIn}
+              setUser={setUser}
+            />
+          } />
```
Comment (Waidhoferj) [inline src/App.js]: The two set__ functions probably don't need to get passed. The ``onAuthStateChanged`` listener will be triggered whenever you log in. This also allows for automatic login, which would be a killer feature. Fire off the set events when ``user`` is passed in the Firebase callback.

File: src/components/SignOut/SignOut.js [hunk 3]
```diff
@@ -1,14 +1,17 @@
...
+  let history = useHistory();
+
   let signOutUser = async () => {
     auth
       .signOut()
       .then(() => {
-        //navigate to Login
+        props.setSignedIn(false);
+        history.push("/login");
       })
```
Comment (Waidhoferj) [inline src/components/SignOut/SignOut.js]: I'd handle this at the ``App.js`` level with the ``onAuthStateChanged`` listener.

File: src/pages/Login/Login.js [hunk 4]
```diff
@@ -10,27 +10,33 @@ export default function Login(props) {
...
   return (
     <div className="Login">
-      <div className="login-container">
+      <div className="account-container">
         <div className="account-title">
           <h2>Log In</h2>
           <div className="header-hr"></div>
         </div>
-        <form onSubmit={(e) => e.preventDefault()}>
+        <form onSubmit={logInUser}>
```
Comment (Waidhoferj) [inline src/pages/Login/Login.js:37]: Nice, hit two birds with one stone!

**Review by Waidhoferj — DISMISSED** [review]

File: src/App.js (hunk 2 above)
Comment (masonmcelvain) [reply src/App.js]: Automatic login would be great! Thanks for pointing that out, I didn't realize that `onAuthStateChanged` listener would be called for every login and logout. I changed it so that the set_ functions aren't passed to the Login or Validator components, and they are instead updated in the listener's callback in App.js itself. The app's behavior still seems the same.

**Review by Waidhoferj — APPROVED** [review]
Nice!
